### ISSUE TITLE
Input dataset format

### ISSUE THREAD

**Issue by prvernier** [beaconsproject/RDMExplorer#16]
@edwardsmarc - do you think that if we converted the gpkg and tif files to .Rdata or Rds or whatever improved loading speed? Esp., with the shinyapps server?

**Comment by edwardsmarc** [comment]
Probably. Since they would already be sf objects. Definitely worth a try.

**Comment by prvernier** [comment]
Okay, I'll try that and time the difference and report back.

**Comment by prvernier** [comment]
I did a quick test of a gpkg layer and a tif file and the improvements don't seem to be significant compared to other functions e.g., leaflet drawing. I'm closing this issue for now but not against revisiting in the future.
