### ISSUE TITLE
Add loading gif using shinycssloaders

### ISSUE THREAD

**Issue by edwardsmarc** [beaconsproject/RDMExplorer#19]
Should be added to all Leaflet maps. See ui in [conservation area explorer](https://github.com/beaconsproject/conservation_area_explorer/blob/master/app.R)

**Comment by edwardsmarc** [comment]
@prvernier What do you think of this? I like the loading symbol but it also removes the map in the background which I don't like. I'm happy to revert to the original behavior if we don't like this addition.

**Comment by prvernier** [comment]
I like it!
