### ISSUE TITLE
Shiny app not working on shinyapps.io server

### ISSUE THREAD

**Issue by prvernier** [beaconsproject/RDMExplorer#2]
The shiny app works fine when run on a local computer but generates errors on shinyapps.io. We need to check log files and determine what the errors are and fix the issue.

**Comment by edwardsmarc** [comment]
Update, fixed the main issue which was a file path issue. App now works but crashed when trying to load the landcover dataset. Log file says out of memory.

**Comment by prvernier** [comment]
I replaced the 30m landcover rasters with 300m rasters and this seems to have fixed the problem when running the app on the shinyapps.io server.
