### ISSUE TITLE
Make sidebar widgets conditional on tab

### ISSUE THREAD

**Issue by edwardsmarc** [beaconsproject/RDMExplorer#20]
e.g. we don't need the 'upstream disturbances' button visible in the footprint tab.
Decide which widgets are needed in which tab and add conditional panels to control them.
See ui in [conservation area explorer](https://github.com/beaconsproject/conservation_area_explorer/blob/master/app.R)

**Comment by edwardsmarc** [comment]
@prvernier What do you think about this proposal? We would have the following input widgets for each tab:

Overview - no widgets
Footprint - FDA, sliders, intactness button, download button
Landcover + Hydrology - FDA, sliders, intactness button (its nice to be able to re-generate the footprint from these tabs)
Upstream - Gen upstream button (this tab doesn't use the footprint so no point having the inputs)

**Comment by prvernier** [comment]
Yes, I like the idea of conditional widgets this proposal makes sense.
