### ISSUE TITLE
Speeding up the display of maps

### ISSUE THREAD

**Issue by prvernier** [beaconsproject/RDMExplorer#3]
Currently, the app reloads the input data each time an event is triggered. This can take some time since some datasets, for example the stream network, are large and load slowly. It may be possible to speed things up by simplifying some of the linework (e.g., for streams) or using some caching system e.g., the reproducible package.

**Comment by edwardsmarc** [comment]
Displaying landcover map types could be faster

**Comment by edwardsmarc** [comment]
Footprint map

* When goButton is pressed, leaflet proxy should remove the footprint and intactness layers, recalculate them in a separate eventReactive, then add them back to the leaflet map. This way the base map object doesn't change, only the footprint and intactness layers.
* Everything that uses the footprint as input should be a reactive that will then auto update. e.g. the intactness table

**Comment by edwardsmarc** [comment]
Land cover and Footprint have been addressed. Remaining is streams map.
